"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useCallback,useEffect,useRef,useState} from 'react';
import {Workflow,Shapes,FolderOpen,History,CircleHelp,ChevronRight,ChevronDown,Plus,Search,Undo2,Redo2,MousePointer2,Hand,MoveRight,Maximize,Minus,Download,Upload,Play,Square,PanelLeftClose,PanelLeftOpen,SlidersHorizontal,CheckCheck,AlertTriangle,CheckCircle2,X,Code2,Presentation,Copy,Trash2,Save,Map,GitBranch,ArrowLeft,ArrowRight,FileCode2,Image,FileText,ShoppingCart,Warehouse,MessagesSquare,AlarmClock,Keyboard,Layers,Route,AlignLeft,AlignCenter,AlignStartVertical,AlignEndVertical,Palette,LoaderCircle,ShieldCheck,PanelRightOpen,ClipboardList,Receipt,CalendarRange,Calculator,Banknote,BookCheck} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem,DropdownMenuSeparator,DropdownMenuLabel} from '@/components/ui/dropdown-menu';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {CommandDialog,CommandInput,CommandList,CommandEmpty,CommandGroup,CommandItem} from '@/components/ui/command';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Tooltip,TooltipContent,TooltipTrigger,TooltipProvider} from '@/components/ui/tooltip';
import {Toaster} from '@/components/ui/sonner';
import {toast} from 'sonner';
import {catalog} from '@/lib/bpmn/catalog';
import {templates} from '@/lib/bpmn/templates.mjs';
import {getStoryElements} from '@/lib/bpmn/graph.mjs';
import {useStudio,type StudioController} from './useStudio';
import './studio.css';
import {Explorer} from './Explorer';

const templateIcons:Record<string,any>={ShoppingCart,Warehouse,GitBranch,MessagesSquare,AlarmClock,Plus,ClipboardList,ShieldCheck,Receipt,Undo2,CalendarRange,Calculator,Banknote,BookCheck};
function IconButton({label,children,onClick,active=false,disabled=false,...rest}:any){return <Tooltip><TooltipTrigger asChild><button className={'icon-button '+(active?'is-active':'')} aria-label={label} aria-pressed={active} onClick={onClick} disabled={disabled} {...rest}>{children}</button></TooltipTrigger><TooltipContent>{label}</TooltipContent></Tooltip>;}
const formatDate=(date:string)=>new Date(date).toLocaleString('vi-VN',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});
function MiniProcess({color='blue'}:{color?:string}){return <svg className={'mini-process '+color} viewBox="0 0 300 100" aria-hidden="true"><path d="M35 50H75M135 50H161M189 50H225M175 64V82H105V64" fill="none" stroke="currentColor" strokeWidth="1.6"/><circle cx="25" cy="50" r="10" fill="white" stroke="currentColor" strokeWidth="2"/><rect x="75" y="32" width="60" height="36" rx="6" fill="white" stroke="currentColor" strokeWidth="1.7"/><path d="m175 36 14 14-14 14-14-14z" fill="white" stroke="currentColor" strokeWidth="1.7"/><path d="m171 46 8 8m0-8-8 8" stroke="currentColor"/><rect x="225" y="32" width="45" height="36" rx="6" fill="white" stroke="currentColor" strokeWidth="1.7"/><path d="M90 46h28m-28 8h18M236 46h23m-23 8h16" stroke="currentColor" opacity=".4" strokeWidth="2"/></svg>;}

function Properties({studio:s,open,onOpenChange}: {studio:StudioController;open:boolean;onOpenChange:(o:boolean)=>void}) {
  const container=useRef<HTMLDivElement|null>(null);
  const attach=useCallback((node:HTMLDivElement|null)=>{container.current=node;const pp=s.modeler.current?.get('propertiesPanel');if(node)pp?.attachTo(node);else pp?.detach();},[s.modeler]);
  useEffect(()=>()=>s.modeler.current?.get('propertiesPanel')?.detach(),[s.modeler]);
  return <Sheet open={open} onOpenChange={onOpenChange} modal={false}><SheetContent className="properties-sheet" onOpenAutoFocus={e=>e.preventDefault()} onInteractOutside={e=>{if((e.target as HTMLElement)?.closest('.canvas-frame'))e.preventDefault();}}><SheetHeader><SheetTitle>Thuộc tính BPMN</SheetTitle><SheetDescription>Chọn phần tử trên sơ đồ để chỉnh sửa.</SheetDescription></SheetHeader><div className="properties-panel-host" ref={attach}/><div className="panel-note"><ShieldCheck size={16}/><span>Thay đổi được lưu vào BPMN XML. Thuộc tính Camunda 7 dành cho tích hợp engine.</span></div></SheetContent></Sheet>;
}

export default function BpmnStudio(){
  const s=useStudio();
  const [exploring,setExploring]=useState(false);
  const [section,setSection]=useState('shapes'),[sidebar,setSidebar]=useState(true),[shapeQuery,setShapeQuery]=useState(''),[searchOpen,setSearchOpen]=useState(false),[templatesOpen,setTemplatesOpen]=useState(false),[helpOpen,setHelpOpen]=useState(false),[propsOpen,setPropsOpen]=useState(false),[xmlOpen,setXmlOpen]=useState(false),[xmlDraft,setXmlDraft]=useState(''),[xmlBusy,setXmlBusy]=useState(false),[deleteId,setDeleteId]=useState<string|null>(null),[renameOpen,setRenameOpen]=useState(false),[nameDraft,setNameDraft]=useState(''),[routeFrom,setRouteFrom]=useState(''),[routeTo,setRouteTo]=useState(''),[grid,setGrid]=useState(true),[tool,setTool]=useState('select');
  const fileInput=useRef<HTMLInputElement>(null);
  const latest=useRef(s);latest.current=s;
  useEffect(()=>{if(window.innerWidth<760)setSidebar(false);},[]);
  const editable=s.ready&&!s.loading&&!s.simulating&&!s.presenting;
  useEffect(()=>{const key=(e:KeyboardEvent)=>{const form=(e.target as HTMLElement).closest('input,textarea,select,[contenteditable="true"],[role="dialog"]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();void latest.current.exportFile('bpmn');}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setSearchOpen(x=>!x);}else if(e.key==='Escape'&&latest.current.presenting){latest.current.togglePresentation();}else if(!form&&e.key==='?'&&!e.ctrlKey&&!e.metaKey){setHelpOpen(true);}else if(!form&&latest.current.presenting&&(e.key==='ArrowRight'||e.key==='ArrowLeft')){e.preventDefault();latest.current.story(e.key==='ArrowRight'?1:-1);}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[]);
  const nodes=s.elements.filter(e=>!e.waypoints&&e.businessObject?.$instanceOf('bpmn:FlowNode'));
  const lanes=s.elements.filter(e=>e.type==='bpmn:Lane');
  const tasks=nodes.filter(e=>e.businessObject?.$instanceOf('bpmn:Activity'));
  const gateways=nodes.filter(e=>e.businessObject?.$instanceOf('bpmn:Gateway'));
  const errors=s.issues.filter(i=>i.severity==='error');
  const selectedName=s.selected?.businessObject?.name||s.selected?.id;
  const storySteps=getStoryElements(s.elements);
  const changeSection=(value:string)=>{setSidebar(true);setSection(value);};
  const openXML=async()=>{try{await s.flush();const {xml}=await s.modeler.current.saveXML({format:true});setXmlDraft(xml);setXmlOpen(true);}catch(e:any){toast.error(e.message);}};
  const chooseTool=(value:string)=>{setTool(value);const m=s.modeler.current;if(!m)return;try{m.get('dragging').cancel();if(value==='hand')s.action('handTool');else if(value==='connect')s.action('globalConnectTool');else if(value==='space')s.action('spaceTool');}catch{if(value==='hand')s.action('handTool');else if(value==='connect')s.action('globalConnectTool');}};
  const exportMenu=<DropdownMenu><DropdownMenuTrigger asChild><Button className="export-button" disabled={!s.ready||s.loading}><Download size={16}/><span>Xuất file</span><ChevronDown size={14}/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-64"><DropdownMenuLabel>Xuất quy trình</DropdownMenuLabel>{[['bpmn','BPMN 2.0 XML',FileCode2],['svg','SVG · vector',Shapes],['png','PNG · độ phân giải 2×',Image],['html','HTML · xem tương tác offline',Code2],['md','Markdown · tài liệu quy trình',FileText]].map(([type,label,Icon]:any)=><DropdownMenuItem key={type} onSelect={()=>void s.exportFile(type)}><Icon/>{label}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu>;

  return <TooltipProvider delayDuration={300}><SidebarProvider className={'studio-root '+(s.presenting?'presentation-mode':'')} style={{'--sidebar-width':'64px'} as React.CSSProperties}><Explorer studio={s} open={exploring} onClose={()=>setExploring(false)}/><Toaster position="bottom-right" theme="light" richColors/>
    <Sidebar collapsible="none" className="app-rail"><SidebarHeader><div className="app-mark" aria-label="BPMN Studio"><Workflow size={25}/></div></SidebarHeader><SidebarContent><SidebarMenu>{[{key:'shapes',label:'Thư viện BPMN',icon:Shapes},{key:'documents',label:'Quy trình trên máy',icon:FolderOpen},{key:'validate',label:'Kiểm tra quy trình',icon:CheckCheck},{key:'routes',label:'Khám phá luồng',icon:Route},{key:'history',label:'Lịch sử phiên bản',icon:History}].map(({key,label,icon:Icon})=><SidebarMenuItem key={key}><SidebarMenuButton tooltip={label} isActive={section===key&&sidebar} className="rail-button" onClick={()=>changeSection(key)} aria-label={label}><Icon size={22}/></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><SidebarMenuButton tooltip="Hướng dẫn & phím tắt" className="rail-button" onClick={()=>setHelpOpen(true)} aria-label="Hướng dẫn & phím tắt"><CircleHelp size={22}/></SidebarMenuButton><div className="rail-avatar">DD</div></SidebarFooter></Sidebar>
    <div className="studio-app"><header className="app-header"><a href="/" className="wordmark">BPMN<span>studio</span><span className="version-label">1.0</span></a><div className="workspace-breadcrumb">Không gian làm việc<ChevronRight size={14}/><span>Quy trình nội bộ</span></div><div className="header-right"><button className="global-search" onClick={()=>setSearchOpen(true)}><Search size={16}/><span>Tìm trong quy trình</span><kbd>⌘ K</kbd></button><span className="local-pill"><span/>Cục bộ</span><IconButton label="Hướng dẫn" onClick={()=>setHelpOpen(true)}><CircleHelp size={19}/></IconButton></div></header>
    <div className="document-header"><div className="document-icon"><Workflow size={23}/></div><div className="document-heading"><button className="document-title" onClick={()=>{setNameDraft(s.active?.name||'');setRenameOpen(true);}} disabled={!editable}>{s.active?.name||'Yêu cầu mua hàng'}<ChevronDown size={16}/></button><div className="save-state"><CheckCheck size={13}/><span>{s.saved}</span><span className="meta-divider">·</span><span>BPMN 2.0</span></div></div><div className="document-actions"><Button variant="outline" onClick={()=>setExploring(true)} disabled={!s.ready}>Khám phá</Button><Button variant="outline" className="import-button" onClick={()=>fileInput.current?.click()} disabled={!editable}><Upload size={16}/><span>Nhập BPMN</span></Button><Button variant="outline" className="present-button" onClick={()=>{setPropsOpen(false);s.togglePresentation();}} disabled={!s.ready||s.loading}><Presentation size={16}/><span>{s.presenting?'Thoát trình bày':'Trình bày'}</span></Button>{exportMenu}</div></div>
    <div className="editor-toolbar"><div className="tools-left"><IconButton label={sidebar?'Ẩn thư viện':'Hiện thư viện'} onClick={()=>setSidebar(x=>!x)}>{sidebar?<PanelLeftClose size={18}/>:<PanelLeftOpen size={18}/>}</IconButton><div className="tool-divider"/><IconButton label="Hoàn tác · Ctrl Z" disabled={!editable||!s.undo} onClick={()=>s.action('undo')}><Undo2 size={18}/></IconButton><IconButton label="Làm lại · Ctrl Shift Z" disabled={!editable||!s.redo} onClick={()=>s.action('redo')}><Redo2 size={18}/></IconButton><div className="tool-divider"/>{[{id:'select',label:'Chọn phần tử',icon:MousePointer2},{id:'hand',label:'Di chuyển canvas · H',icon:Hand},{id:'connect',label:'Nối phần tử · C',icon:MoveRight}].map(({id,label,icon:Icon})=><IconButton key={id} label={label} active={tool===id} disabled={!editable} onClick={()=>chooseTool(id)}><Icon size={18}/></IconButton>)}<DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label="Căn chỉnh nhiều phần tử" disabled={!editable||s.selectionCount<2}><AlignLeft size={18}/></button></DropdownMenuTrigger><DropdownMenuContent>{[['left','Căn trái',AlignLeft],['center','Căn giữa',AlignCenter],['top','Căn trên',AlignStartVertical],['bottom','Căn dưới',AlignEndVertical]].map(([type,label,Icon]:any)=><DropdownMenuItem key={type} onSelect={()=>s.action('alignElements',{type})}><Icon/>{label}</DropdownMenuItem>)}<DropdownMenuSeparator/><DropdownMenuItem onSelect={()=>s.action('distributeElements',{type:'horizontal'})}>Phân bố ngang</DropdownMenuItem><DropdownMenuItem onSelect={()=>s.action('distributeElements',{type:'vertical'})}>Phân bố dọc</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div>
    <Tabs className="mode-tabs" value={s.presenting?'present':s.simulating?'simulate':'design'} onValueChange={v=>{setPropsOpen(false);if(v==='simulate'&&!s.simulating)s.toggleSimulation();if(v==='design'){if(s.simulating)s.toggleSimulation();if(s.presenting)s.togglePresentation();}if(v==='present'&&!s.presenting)s.togglePresentation();}}><TabsList><TabsTrigger value="design" disabled={!s.ready}>Thiết kế</TabsTrigger><TabsTrigger value="simulate" disabled={!s.ready}><Play size={13}/>Mô phỏng</TabsTrigger><TabsTrigger value="present" disabled={!s.ready}>Trình bày</TabsTrigger></TabsList></Tabs><div className="tools-right"><button className={'validation-button '+(s.issues.length?'has-issues':'')} onClick={()=>changeSection('validate')} disabled={!s.ready}>{s.issues.length?<AlertTriangle size={16}/>:<CheckCircle2 size={16}/>}<span>{s.issues.length?`${s.issues.length} cần kiểm tra`:'Kiểm tra quy trình'}</span></button><div className="tool-divider"/><IconButton label="Xem & sửa BPMN XML" onClick={()=>void openXML()} disabled={!s.ready}><Code2 size={18}/></IconButton><IconButton label="Thuộc tính BPMN" onClick={()=>setPropsOpen(x=>!x)} active={propsOpen} disabled={!editable}><SlidersHorizontal size={18}/></IconButton></div></div>
    <div className="editor-body">
      {sidebar&&!s.presenting&&<aside className="library-panel"><div className="library-header"><h2>{{shapes:'Thư viện BPMN',documents:'Quy trình trên máy',validate:'Kiểm tra quy trình',routes:'Khám phá luồng',history:'Mốc phiên bản'}[section]}</h2><IconButton label="Đóng bảng" onClick={()=>setSidebar(false)}><X size={16}/></IconButton></div>
      {section==='shapes'&&<><div className="library-top"><button className="template-shortcut" onClick={()=>setTemplatesOpen(true)} disabled={!editable}><div className="template-shortcut-icon"><Layers size={20}/></div><span><strong>Bắt đầu từ mẫu</strong><small>Quy trình nghiệp vụ thực tế</small></span><ChevronRight size={16}/></button><div className="input-with-icon"><Search size={16}/><Input aria-label="Tìm ký hiệu BPMN" placeholder="Tìm ký hiệu…" value={shapeQuery} onChange={e=>setShapeQuery(e.target.value)}/></div></div><div className="palette-scroll">{['Sự kiện','Tác vụ','Cổng điều kiện','Cấu trúc','Dữ liệu & ghi chú'].map((group,index)=>{const entries=catalog.filter(e=>e.group===group&&(e.name+' '+e.type).toLocaleLowerCase().includes(shapeQuery.toLocaleLowerCase()));return entries.length?<details className="palette-group" key={group} open={shapeQuery?true:undefined} {...(!shapeQuery?{name:undefined}: {})}><summary>{group}<span>{entries.length}</span><ChevronDown size={14}/></summary><div className="palette-grid">{entries.map(entry=><button key={entry.name} disabled={!editable} className={'palette-item group-'+index} onMouseDown={e=>{if(e.button===0){e.preventDefault();s.create(entry,e);}}} onTouchStart={e=>s.create(entry,e)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();s.create(entry,e);}}} title={entry.hint||entry.type}><i className={entry.icon} aria-hidden="true"/><span>{entry.name}</span></button>)}</div></details>:null;})}{!catalog.some(e=>(e.name+' '+e.type).toLocaleLowerCase().includes(shapeQuery.toLocaleLowerCase()))&&<div className="empty-small">Không tìm thấy ký hiệu.</div>}<div className="quick-palette"><span className="eyebrow">THƯỜNG DÙNG</span><div className="palette-grid">{catalog.filter(e=>['Bắt đầu','Người thực hiện','Lựa chọn · XOR','Kết thúc'].includes(e.name)).map(entry=><button key={entry.name} disabled={!editable} className="palette-item" onMouseDown={e=>{if(e.button===0){e.preventDefault();s.create(entry,e);}}} onTouchStart={e=>s.create(entry,e)}><i className={entry.icon} aria-hidden="true"/><span>{entry.name}</span></button>)}</div></div></div><div className="library-footer"><MousePointer2 size={17}/><p>Kéo ký hiệu vào canvas.<br/>Nhấp đôi để sửa tên.</p></div></>}
      {section==='documents'&&<div className="side-content"><Button onClick={()=>setTemplatesOpen(true)} disabled={!editable} className="w-full"><Plus size={16}/>Tạo quy trình</Button><p className="side-description">Tự động lưu trên trình duyệt này. Xuất BPMN để sao lưu hoặc chuyển máy.</p><div className="document-list">{s.documents.map(doc=><div key={doc.id} className={'document-item '+(doc.id===s.activeId?'active':'')}><button onClick={()=>void s.switchDocument(doc.id)} disabled={s.loading}><Workflow size={18}/><span><strong>{doc.name}</strong><small>{formatDate(doc.updatedAt)}</small></span></button><IconButton label={'Xóa '+doc.name} disabled={!editable} onClick={()=>setDeleteId(doc.id)}><Trash2 size={15}/></IconButton></div>)}</div><Button variant="outline" className="w-full" onClick={()=>void s.duplicate()} disabled={!editable}><Copy size={15}/>Nhân bản quy trình</Button></div>}
      {section==='validate'&&<div className="side-content"><div className={'validation-summary '+(s.issues.length?'warning':'success')}>{s.issues.length?<AlertTriangle size={27}/>:<ShieldCheck size={30}/>}<strong>{s.issues.length?`${errors.length} lỗi · ${s.issues.length-errors.length} lưu ý`:'Chưa phát hiện vấn đề'}</strong><p>Kiểm tra cấu trúc, điều kiện nhánh và sự kiện. Không thay thế chứng nhận toàn bộ chuẩn BPMN.</p></div>{s.issues.map((issue,i)=><button className="issue-card" key={issue.id+issue.code+i} onClick={()=>s.focus(issue.id)}><span className={'issue-dot '+issue.severity}/><div><strong>{s.elements.find(e=>e.id===issue.id)?.businessObject?.name||issue.id}</strong><p>{issue.message}</p><small>{issue.code}</small></div><ChevronRight size={13}/></button>)}<Button variant="outline" className="w-full" onClick={()=>s.refresh()} disabled={!s.ready}><CheckCheck size={16}/>Kiểm tra lại</Button></div>}
      {section==='routes'&&<div className="side-content"><p className="side-description">Khám phá các bước liên quan theo chiều Sequence Flow.</p><label className="field-label">Vai trò / Lane</label><Select value={s.lens.startsWith('lane:')?s.lens:'all'} onValueChange={v=>s.highlight(v)}><SelectTrigger className="w-full"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Tất cả vai trò</SelectItem>{lanes.map(l=><SelectItem key={l.id} value={'lane:'+l.id}>{l.businessObject.name||l.id}</SelectItem>)}</SelectContent></Select><div className="side-separator"/><span className="eyebrow">TỪ BƯỚC ĐANG CHỌN</span><p className="selected-node-label">{selectedName||'Chưa chọn bước'}</p><div className="two-buttons"><Button variant="outline" onClick={()=>s.highlight('upstream')} disabled={!s.selected}><ArrowLeft size={14}/>Trước đó</Button><Button variant="outline" onClick={()=>s.highlight('downstream')} disabled={!s.selected}>Sau đó<ArrowRight size={14}/></Button></div><div className="side-separator"/><span className="eyebrow">TÌM ĐƯỜNG ĐI</span><label className="field-label">Điểm đầu</label><Select value={routeFrom} onValueChange={setRouteFrom}><SelectTrigger className="w-full"><SelectValue placeholder="Chọn bước bắt đầu"/></SelectTrigger><SelectContent>{nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.businessObject.name||n.id}</SelectItem>)}</SelectContent></Select><label className="field-label">Điểm cuối</label><Select value={routeTo} onValueChange={setRouteTo}><SelectTrigger className="w-full"><SelectValue placeholder="Chọn bước kết thúc"/></SelectTrigger><SelectContent>{nodes.map(n=><SelectItem key={n.id} value={n.id}>{n.businessObject.name||n.id}</SelectItem>)}</SelectContent></Select><Button className="w-full mt-4" disabled={!routeFrom||!routeTo} onClick={()=>s.route(routeFrom,routeTo)}><Route size={16}/>Tìm đường đi</Button><button className="text-button" onClick={()=>s.highlight('all')}>Xóa vùng làm nổi bật</button><p className="side-description">Đường đi cho thấy kết nối cấu trúc; điều kiện thực tế có thể chọn nhánh khác.</p></div>}
      {section==='history'&&<div className="side-content"><Button className="w-full" disabled={!editable} onClick={()=>void s.checkpoint('Phiên bản '+((s.active?.revisions.length||0)+1))}><Save size={16}/>Lưu mốc phiên bản</Button><p className="side-description">Giữ 12 mốc gần nhất trên máy này. Trước khi khôi phục, bản hiện tại được lưu thành một mốc.</p>{s.active?.revisions.length?s.active.revisions.map(rev=><div className="revision-card" key={rev.id}><History size={18}/><div><strong>{rev.label}</strong><small>{formatDate(rev.createdAt)}</small><button className="text-button" disabled={!editable} onClick={()=>void s.restore(rev)}>Khôi phục mốc này</button></div></div>):<div className="empty-state"><History size={36}/><strong>Chưa có mốc phiên bản</strong><p>Lưu lại khi hoàn tất một phần quy trình để dễ quay lại.</p></div>}</div>}
      </aside>}
      <main className={'canvas-frame '+(!grid?'no-grid':'')+(s.presenting?' read-only':'')} aria-label="Canvas BPMN" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const file=e.dataTransfer.files[0];if(file&&editable)void s.importFile(file);}}>
        <div className="canvas-topline"><div className="canvas-caption"><span className="eyebrow">QUY TRÌNH NGHIỆP VỤ</span><span className="canvas-summary">{tasks.length} tác vụ<span>·</span>{gateways.length} gateway<span>·</span>{lanes.length} vai trò</span></div><div className="canvas-top-actions"><button onClick={()=>{setSidebar(true);setSection('routes');}}><Layers size={14}/>{s.lens==='all'?'Tất cả vai trò':'Đang làm nổi bật'}<ChevronDown size={13}/></button>{s.lens!=='all'&&<IconButton label="Hiện tất cả" onClick={()=>s.highlight('all')}><X size={15}/></IconButton>}</div></div>
        <div className="bpmn-canvas" ref={s.canvasRef} tabIndex={0} aria-label="Vùng chỉnh sửa sơ đồ BPMN"/>
        {s.loading&&<div className="canvas-loading"><LoaderCircle className="animate-spin" size={30}/><strong>Đang mở quy trình…</strong></div>}
        {s.error&&<div className="canvas-loading error-state"><AlertTriangle size={32}/><strong>Không mở được trình biên tập</strong><p>{s.error}</p><Button onClick={()=>window.location.reload()}>Thử lại</Button></div>}
        {s.simulating&&<div className="simulation-banner"><span className="simulation-dot"/><div><strong>Mô phỏng token</strong><span>Chọn ▶ trên Start Event để chạy. Chọn nhánh tại gateway.</span></div><Button size="sm" variant="outline" onClick={s.toggleSimulation}><Square size={12}/>Dừng</Button></div>}
        {s.presenting&&<div className="story-panel"><div className="story-step">{s.storyIndex<0?'BPMN':String(s.storyIndex+1).padStart(2,'0')}</div><div><small>TRÌNH BÀY QUY TRÌNH {s.storyIndex>=0?`· ${s.storyIndex+1}/${storySteps.length}`:''}</small><strong>{s.storyIndex<0?'Bắt đầu khám phá':selectedName}</strong><p>{s.storyIndex<0?'Duyệt từng phần tử để giải thích nghiệp vụ. Đây là trình bày, không phải mô phỏng luồng.':s.selected?.businessObject?.documentation?.map((d:any)=>d.text).join(' ')||'Nhấp đôi tên ở chế độ Thiết kế; bổ sung mô tả trong Thuộc tính BPMN.'}</p></div><div className="story-controls"><IconButton label="Bước trước" onClick={()=>s.story(-1)} disabled={s.storyIndex<=0}><ArrowLeft size={18}/></IconButton><Button onClick={()=>s.story(1)} disabled={s.storyIndex===storySteps.length-1}>Tiếp theo<ArrowRight size={16}/></Button><IconButton label="Thoát trình bày · Esc" onClick={s.togglePresentation}><X size={17}/></IconButton></div></div>}
        {s.selected&&!s.simulating&&!s.presenting&&<div className="selection-card"><span className="selection-type">{s.selected.type.replace('bpmn:','')}</span><strong>{selectedName}</strong><div className="selection-actions"><IconButton label="Xem các bước trước" onClick={()=>s.highlight('upstream')}><ArrowLeft size={15}/></IconButton><IconButton label="Xem các bước sau" onClick={()=>s.highlight('downstream')}><ArrowRight size={15}/></IconButton><DropdownMenu><DropdownMenuTrigger asChild><button className="icon-button" aria-label="Đổi màu phần tử" disabled={!editable}><Palette size={16}/></button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuLabel>Màu phần tử</DropdownMenuLabel><div className="color-swatches">{[['#eef4ff','#5477b4'],['#e4f5ee','#298273'],['#fff8e6','#b3812f'],['#fff0f0','#b95560'],['#f2eeff','#8970bd'],['#ffffff','#67788f']].map(([fill,stroke])=><button key={fill} aria-label={'Màu '+stroke} style={{background:fill,borderColor:stroke}} onClick={()=>s.setColor(fill,stroke)}/>)}</div></DropdownMenuContent></DropdownMenu><button className="selection-props" onClick={()=>setPropsOpen(true)}><SlidersHorizontal size={14}/>Thuộc tính</button></div></div>}
        <div className="canvas-bottom-left"><div className="zoom-controls"><IconButton label="Thu nhỏ" onClick={()=>s.changeZoom(1/1.15)} disabled={!s.ready}><Minus size={17}/></IconButton><button className="zoom-number" onClick={s.fit} title="Vừa màn hình">{s.zoom}%</button><IconButton label="Phóng to" onClick={()=>s.changeZoom(1.15)} disabled={!s.ready}><Plus size={17}/></IconButton><span className="tool-divider"/><IconButton label="Vừa màn hình" onClick={s.fit} disabled={!s.ready}><Maximize size={16}/></IconButton></div><div className="view-controls"><IconButton label="Ẩn / hiện minimap" onClick={()=>s.modeler.current?.get('minimap').toggle()} disabled={!s.ready}><Map size={17}/></IconButton><IconButton label="Ẩn / hiện lưới nền" onClick={()=>setGrid(x=>!x)} active={grid}><span className="grid-icon">⠿</span></IconButton></div></div>
        {!s.selected&&!s.simulating&&!s.presenting&&<div className="canvas-hint"><MousePointer2 size={13}/>Chọn một bước để xem chi tiết<kbd>?</kbd></div>}
      </main>
    </div><footer className="app-statusbar"><span><ShieldCheck size={13}/>BPMN 2.0 · Process & Collaboration</span><span className="statusbar-middle">{nodes.length} phần tử<span>·</span>{s.elements.filter(e=>e.type==='bpmn:SequenceFlow').length} luồng</span><button onClick={()=>setHelpOpen(true)}><Keyboard size={14}/>Phím tắt</button></footer></div>

    <input type="file" ref={fileInput} accept=".bpmn,.xml" className="sr-only" onChange={e=>{const file=e.target.files?.[0];if(file)void s.importFile(file);e.target.value='';}}/>
    <Properties studio={s} open={propsOpen&&editable} onOpenChange={setPropsOpen}/>
    <Dialog open={templatesOpen} onOpenChange={setTemplatesOpen}><DialogContent className="template-dialog"><DialogHeader><span className="eyebrow">THƯ VIỆN QUY TRÌNH</span><DialogTitle>Bắt đầu với một quy trình thực tế.</DialogTitle><DialogDescription>Chọn mẫu để tạo bản riêng và điều chỉnh theo nghiệp vụ.</DialogDescription></DialogHeader><div className="template-grid">{templates.map(t=>{const Icon=templateIcons[t.icon];return <button key={t.id} className="template-card" disabled={!editable} onClick={async()=>{const ok=await s.newFromTemplate(t.id);if(ok){setTemplatesOpen(false);setSection('shapes');}}}><div className={'template-preview '+t.color}><MiniProcess color={t.color}/><span>{t.category}</span></div><div className="template-content"><Icon size={20}/><strong>{t.name}</strong><p>{t.description}</p><span>Sử dụng mẫu<ArrowRight size={14}/></span></div></button>;})}</div></DialogContent></Dialog>
    <CommandDialog open={searchOpen} onOpenChange={setSearchOpen} title="Tìm phần tử BPMN" description="Tìm theo tên hoặc mã phần tử."><CommandInput placeholder="Tìm tác vụ, sự kiện, gateway…"/><CommandList><CommandEmpty>Không tìm thấy phần tử.</CommandEmpty><CommandGroup heading="Trong quy trình đang mở">{s.elements.filter(e=>e.type!=='bpmn:Process'&&e.type!=='bpmn:Collaboration').map(e=><CommandItem key={e.id} value={e.id+' '+e.businessObject?.name} onSelect={()=>{s.focus(e.id);setSearchOpen(false);}}><Workflow size={16}/><span>{e.businessObject?.name||e.id}</span><small className="ml-auto text-muted-foreground">{e.type.replace('bpmn:','')}</small></CommandItem>)}</CommandGroup></CommandList></CommandDialog>
    <Dialog open={xmlOpen} onOpenChange={setXmlOpen}><DialogContent className="xml-dialog"><DialogHeader><DialogTitle>BPMN 2.0 XML</DialogTitle><DialogDescription>XML kèm bố cục BPMNDI. Bản hiện tại được lưu thành mốc trước khi áp dụng thay đổi.</DialogDescription></DialogHeader><textarea className="xml-editor" value={xmlDraft} onChange={e=>setXmlDraft(e.target.value)} spellCheck={false} aria-label="Mã nguồn BPMN XML" readOnly={!editable}/><DialogFooter><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(xmlDraft);toast.success('Đã sao chép XML.');}catch{toast.error('Không truy cập được clipboard. Có thể chọn và sao chép trong ô XML.');}}}><Copy size={15}/>Sao chép</Button><Button disabled={!editable||xmlBusy} onClick={async()=>{setXmlBusy(true);try{const ok=await s.applyXML(xmlDraft);if(ok)setXmlOpen(false);}catch(e:any){toast.error(e.message);}finally{setXmlBusy(false);}}}>{xmlBusy?<LoaderCircle size={16} className="animate-spin"/>:<CheckCheck size={16}/>}Áp dụng XML</Button></DialogFooter></DialogContent></Dialog>
    <Dialog open={renameOpen} onOpenChange={setRenameOpen}><DialogContent><DialogHeader><DialogTitle>Đổi tên quy trình</DialogTitle><DialogDescription>Tên hiển thị và tên file khi xuất.</DialogDescription></DialogHeader><Input value={nameDraft} onChange={e=>setNameDraft(e.target.value)} maxLength={120} aria-label="Tên quy trình" onKeyDown={e=>{if(e.key==='Enter'&&nameDraft.trim()){s.rename(nameDraft);setRenameOpen(false);}}}/><DialogFooter><Button disabled={!nameDraft.trim()} onClick={()=>{s.rename(nameDraft);setRenameOpen(false);}}>Lưu tên</Button></DialogFooter></DialogContent></Dialog>
    <AlertDialog open={!!deleteId} onOpenChange={o=>{if(!o)setDeleteId(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa quy trình khỏi máy này?</AlertDialogTitle><AlertDialogDescription>Quy trình và các mốc phiên bản đã lưu trên trình duyệt sẽ bị xóa. Hãy xuất file BPMN nếu cần giữ lại.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Giữ lại</AlertDialogCancel><AlertDialogAction onClick={()=>{if(deleteId)void s.removeDocument(deleteId);setDeleteId(null);}}>Xóa quy trình</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
    <Dialog open={helpOpen} onOpenChange={setHelpOpen}><DialogContent className="help-dialog"><DialogHeader><span className="eyebrow">BPMN STUDIO</span><DialogTitle>Từ nghiệp vụ đến quy trình rõ ràng.</DialogTitle><DialogDescription>Thiết kế, thảo luận và kiểm tra luồng ngay trong trình duyệt.</DialogDescription></DialogHeader><div className="help-grid"><section><h3>Bắt đầu nhanh</h3><ol><li>Mở <strong>Thư viện BPMN → Bắt đầu từ mẫu</strong>, hoặc nhập file .bpmn.</li><li>Kéo ký hiệu vào canvas. Nhấp đôi để đặt tên.</li><li>Chọn phần tử và mở biểu tượng cờ lê của BPMN để đổi loại, loop, multi-instance. Chọn Pool để thêm Lane.</li><li>Nối phần tử bằng công cụ <strong>C</strong>. Các quy tắc xác định Sequence Flow, Message Flow hoặc Association hợp lệ.</li><li>Mở <strong>Thuộc tính</strong> để đặt điều kiện, timer, message, documentation và tham số engine.</li><li>Chạy kiểm tra, mô phỏng token, rồi xuất file.</li></ol><h3>Lưu & chia sẻ</h3><p>Quy trình và 12 mốc phiên bản được lưu cục bộ. Xuất <strong>HTML</strong> để gửi bản xem tương tác mở offline; xuất <strong>BPMN</strong> để tiếp tục chỉnh sửa ở công cụ tương thích.</p></section><section><h3>Phím tắt</h3><div className="shortcut-list">{[['Ctrl / ⌘ Z','Hoàn tác'],['Ctrl / ⌘ Shift Z','Làm lại'],['Ctrl / ⌘ C, V','Sao chép, dán phần tử'],['Ctrl / ⌘ S','Xuất file BPMN'],['Ctrl / ⌘ K','Tìm phần tử'],['H / L / C','Di chuyển / chọn vùng / nối'],['E / R','Đổi tên / thay loại'],['Delete','Xóa phần tử'],['← / →','Bước trước / sau khi trình bày'],['Esc','Thoát trình bày']].map(([key,label])=><div key={key}><span>{label}</span><kbd>{key}</kbd></div>)}</div><div className="scope-note"><h3>Phạm vi hỗ trợ</h3><p><strong>Process & Collaboration BPMN 2.0.</strong> Ký hiệu nâng cao dùng menu thay loại theo ngữ cảnh. Choreography và Conversation chưa được hỗ trợ.</p><p>Mô phỏng token không thực thi API, email, script hay biểu thức nghiệp vụ. Quy trình cần cấu hình engine và kiểm thử triển khai trước khi chạy thực tế.</p></div></section></div></DialogContent></Dialog>
  </SidebarProvider></TooltipProvider>;
}
