export type PaletteEntry = {name:string; type:string; icon:string; group:string; event?:string; attrs?:Record<string,unknown>; expanded?:boolean; hint?:string};
const task = (name:string,type:string,icon:string):PaletteEntry => ({name,type:'bpmn:'+type,icon:'bpmn-icon-'+icon,group:'Tác vụ'});
const event = (name:string,type:string,icon:string,definition?:string,attrs?:Record<string,unknown>):PaletteEntry => ({name,type:'bpmn:'+type,icon:'bpmn-icon-'+icon,group:'Sự kiện',event:definition ? 'bpmn:'+definition+'EventDefinition' : undefined,attrs});
export const catalog:PaletteEntry[] = [
  event('Bắt đầu','StartEvent','start-event-none'),
  event('Bắt đầu · thông điệp','StartEvent','start-event-message','Message'),
  event('Bắt đầu · hẹn giờ','StartEvent','start-event-timer','Timer'),
  event('Bắt đầu · tín hiệu','StartEvent','start-event-signal','Signal'),
  event('Bắt đầu · điều kiện','StartEvent','start-event-condition','Conditional'),
  event('Chờ thông điệp','IntermediateCatchEvent','intermediate-event-catch-message','Message'),
  event('Chờ thời gian','IntermediateCatchEvent','intermediate-event-catch-timer','Timer'),
  event('Chờ tín hiệu','IntermediateCatchEvent','intermediate-event-catch-signal','Signal'),
  event('Chờ điều kiện','IntermediateCatchEvent','intermediate-event-catch-condition','Conditional'),
  event('Bắt liên kết','IntermediateCatchEvent','intermediate-event-catch-link','Link'),
  event('Sự kiện trung gian','IntermediateThrowEvent','intermediate-event-none'),
  event('Phát thông điệp','IntermediateThrowEvent','intermediate-event-throw-message','Message'),
  event('Phát tín hiệu','IntermediateThrowEvent','intermediate-event-throw-signal','Signal'),
  event('Phát liên kết','IntermediateThrowEvent','intermediate-event-throw-link','Link'),
  event('Phát escalation','IntermediateThrowEvent','intermediate-event-throw-escalation','Escalation'),
  event('Phát bù trừ','IntermediateThrowEvent','intermediate-event-throw-compensation','Compensate'),
  event('Kết thúc','EndEvent','end-event-none'),
  event('Kết thúc · thông điệp','EndEvent','end-event-message','Message'),
  event('Kết thúc · lỗi','EndEvent','end-event-error','Error'),
  event('Kết thúc · tín hiệu','EndEvent','end-event-signal','Signal'),
  event('Kết thúc · escalation','EndEvent','end-event-escalation','Escalation'),
  event('Kết thúc · bù trừ','EndEvent','end-event-compensation','Compensate'),
  event('Kết thúc · terminate','EndEvent','end-event-terminate','Terminate'),
  {...event('Kết thúc · hủy giao dịch','EndEvent','end-event-cancel','Cancel'),hint:'Chỉ đặt trong Transaction Subprocess.'},
  {...event('Biên · hẹn giờ','BoundaryEvent','intermediate-event-catch-timer','Timer'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · không ngắt','BoundaryEvent','intermediate-event-catch-non-interrupting-timer','Timer',{cancelActivity:false}),hint:'Timer tạo nhánh mới, giữ tác vụ hiện tại.'},
  {...event('Biên · lỗi','BoundaryEvent','intermediate-event-catch-error','Error'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · thông điệp','BoundaryEvent','intermediate-event-catch-message','Message'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · tín hiệu','BoundaryEvent','intermediate-event-catch-signal','Signal'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · escalation','BoundaryEvent','intermediate-event-catch-escalation','Escalation'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · bù trừ','BoundaryEvent','intermediate-event-catch-compensation','Compensate'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · điều kiện','BoundaryEvent','intermediate-event-catch-condition','Conditional'),hint:'Kéo vào đường viền của một tác vụ.'},
  {...event('Biên · hủy giao dịch','BoundaryEvent','intermediate-event-catch-cancel','Cancel'),hint:'Chỉ gắn trên Transaction Subprocess.'},
  task('Tác vụ','Task','task-none'),task('Người thực hiện','UserTask','user-task'),task('Dịch vụ / API','ServiceTask','service-task'),task('Thủ công','ManualTask','manual-task'),task('Quy tắc nghiệp vụ','BusinessRuleTask','business-rule-task'),task('Script','ScriptTask','script-task'),task('Gửi thông điệp','SendTask','send-task'),task('Nhận thông điệp','ReceiveTask','receive-task'),
  ...[['Lựa chọn · XOR','ExclusiveGateway','gateway-xor'],['Song song · AND','ParallelGateway','gateway-parallel'],['Bao hàm · OR','InclusiveGateway','gateway-or'],['Theo sự kiện','EventBasedGateway','gateway-eventbased'],['Phức hợp','ComplexGateway','gateway-complex']].map(([name,type,icon]) => ({name,type:'bpmn:'+type,icon:'bpmn-icon-'+icon,group:'Cổng điều kiện'})),
  {name:'Quy trình con',type:'bpmn:SubProcess',icon:'bpmn-icon-subprocess-collapsed',group:'Cấu trúc'},
  {name:'Quy trình con mở rộng',type:'bpmn:SubProcess',icon:'bpmn-icon-subprocess-expanded',group:'Cấu trúc',expanded:true},
  {name:'Event Subprocess',type:'bpmn:SubProcess',icon:'bpmn-icon-event-subprocess-expanded',group:'Cấu trúc',expanded:true,attrs:{triggeredByEvent:true}},
  {name:'Giao dịch',type:'bpmn:Transaction',icon:'bpmn-icon-transaction',group:'Cấu trúc',expanded:true},
  {name:'Ad-hoc Subprocess',type:'bpmn:AdHocSubProcess',icon:'bpmn-icon-subprocess-expanded',group:'Cấu trúc',expanded:true},
  {name:'Call Activity',type:'bpmn:CallActivity',icon:'bpmn-icon-call-activity',group:'Cấu trúc'},
  {name:'Pool / Participant',type:'bpmn:Participant',icon:'bpmn-icon-participant',group:'Cấu trúc',hint:'Thêm Lane bằng menu ngữ cảnh của Pool.'},
  {name:'Đối tượng dữ liệu',type:'bpmn:DataObjectReference',icon:'bpmn-icon-data-object',group:'Dữ liệu & ghi chú'},
  {name:'Kho dữ liệu',type:'bpmn:DataStoreReference',icon:'bpmn-icon-data-store',group:'Dữ liệu & ghi chú'},
  {name:'Chú thích',type:'bpmn:TextAnnotation',icon:'bpmn-icon-text-annotation',group:'Dữ liệu & ghi chú'},
  {name:'Nhóm',type:'bpmn:Group',icon:'bpmn-icon-group',group:'Dữ liệu & ghi chú'}
];

export const translations:Record<string,string> = {
  'General':'Thông tin chung','Name':'Tên','ID':'Mã định danh','Documentation':'Mô tả nghiệp vụ','Element documentation':'Mô tả phần tử','Process documentation':'Mô tả quy trình','Details':'Chi tiết',
  'Process ID':'Mã quy trình','Process name':'Tên quy trình','Executable':'Có thể thực thi','Participant Name':'Tên participant','Participant ID':'Mã participant',
  'Start Event':'Sự kiện bắt đầu','End Event':'Sự kiện kết thúc','User Task':'Tác vụ người dùng','Service Task':'Tác vụ dịch vụ','Task':'Tác vụ',
  'Change element':'Đổi loại phần tử','Append task':'Thêm tác vụ','Append end event':'Thêm kết thúc','Append gateway':'Thêm gateway','Remove':'Xóa',
  'Connect using Sequence/MessageFlow or Association':'Nối bằng Sequence / Message Flow hoặc Association',
  'Condition':'Điều kiện','Condition expression':'Biểu thức điều kiện','Expression':'Biểu thức','Formal expression':'Biểu thức','Type':'Loại','Script':'Script','Script format':'Định dạng script',
  'Timer':'Hẹn giờ','Timer definition type':'Loại hẹn giờ','Timer definition':'Giá trị hẹn giờ','Duration':'Khoảng chờ','Date':'Thời điểm','Cycle':'Chu kỳ',
  'Message':'Thông điệp','Message name':'Tên thông điệp','Message ID':'Mã thông điệp','Signal':'Tín hiệu','Signal name':'Tên tín hiệu','Signal ID':'Mã tín hiệu',
  'Error':'Lỗi','Error name':'Tên lỗi','Error code':'Mã lỗi','Escalation':'Escalation','Link':'Liên kết','Multi-instance':'Đa thể hiện',
  'Loop cardinality':'Số lần lặp','Completion condition':'Điều kiện hoàn tất','Called element':'Quy trình được gọi','Select an element to edit its properties.':'Chọn phần tử để chỉnh thuộc tính.',
  'Search':'Tìm kiếm','Add lane above':'Thêm lane phía trên','Add lane below':'Thêm lane phía dưới','Divide into two lanes':'Chia thành hai lane','Divide into three lanes':'Chia thành ba lane'
};
export function translate(template:string, replacements:Record<string,string> = {}) { return (translations[template] || template).replace(/\{([^}]+)\}/g,(_,key) => replacements[key] ?? '{'+key+'}'); }
